services:
  app:
    image: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    expose:
      - "8000"
    environment:
      - PORT=8000

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app