name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for syntax errors
        run: python -m compileall -f .

      - name: Run linter (flake8)
        run: flake8 . --count --show-source --statistics

      - name: Run type checker (mypy)
        run: mypy .

      - name: Run security check (bandit)
        run: bandit -r .

      - name: Run tests
        run: pytest --exitfirst --strict --tb=short
