name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check for syntax errors
        run: |
          python -m py_compile main.py api/**/*.py tests/**/*.py

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run linter (flake8)
        run: |
          source venv/bin/activate
          flake8 . --count --show-source --statistics

      - name: Run type checker (mypy)
        run: |
          source venv/bin/activate
          mypy .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --exitfirst --strict
