name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check for syntax errors
        run: |
          python -m compileall -f . || exit 1  # Force exit on error

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (flake8)
        run: |
          source venv/bin/activate
          flake8 . --count --show-source --statistics || exit 1  # Fail on lint errors

      - name: Run type checker (mypy)
        run: |
          source venv/bin/activate
          mypy . || exit 1  # Fail on type errors

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --exitfirst --strict --tb=short || exit 1  # Ensure test failures stop the pipeline
