name: CI Pipeline

on:
  push:
    branches:
      - main
# Hello worldasasas
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -x
            export SUDO_ASKPASS="/usr/local/bin/askpass.sh"
            cd /home/oxblixxx/fast-deploy
            echo "hello world" >> test.txt
            git clone https://github.com/oxblixxx/fastapi-book-project.git || true
            cd fastapi-book-project

            # Set up Python virtual environment
            # python3 -m venv venv
            # source venv/bin/activate
            # pip install -r requirements.txt
            # Make mistake
            # Create Docker network (ignore error if it already exists)
            docker network create --subnet=192.168.1.0/24 fastapi || true
            # rerun
            # Build and run FastAPI containersdsd
            docker build -t fastapi-app .
            docker run -d --name fastapi-app --net fastapi --ip 192.168.1.100 -p 8000:8000 fastapi-app
            sudo -A cp /home/oxblixxx/fast-deploy/fastapi-book-project/fast-api /etc/nginx/sites-available/fast-api
            sudo -A ln -sf /etc/nginx/sites-available/fast-api /etc/nginx/sites-enabled/
            sudo -A nginx -t
            sudo -A systemctl restart nginx