name: CD - Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -x  # Enable debugging

            # Navigate to the project directory
            mkdir -p /home/oxblixxx/fastapi-book-project
            cd /home/oxblixxx/fastapi-book-project

            # Fetch and reset to the latest code from the main branch
            git fetch origin main
            git reset --hard origin/main

            # Stop existing containers (if any)
            docker-compose down || true

            # Rebuild and restart Docker containers
            docker-compose up -d --build

            # Check the status of the containers
            docker ps

            # Test the /stage2 endpoint
            curl -I http://localhost:8000/api/stage2 || echo "Endpoint /stage2 is not available"

            # Check Docker logs for errors
            docker-compose logs fastapi-app