name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Deploy Docker container
        run: |
          docker run -d -p 8000:8000 --name fastapi-app fastapi-app

# 
      # - name: Build and deploy with Docker Compose
      #   run: |
      #     docker-compose up -d